name: Publish contracts typechain package
# on: 
#   release:
#     types: 
#       - created
on: workflow_dispatch
jobs:
  Publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    if: |
      startsWith(github.ref, 'refs/tags/@royalty-loans/contracts-typechain') &&
      !contains(github.ref, '-alpha.')

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Setup node"
        uses: actions/setup-node@v5
        with:
          node-version: '22'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@originalworks'
          package-manager-cache: false
          always-auth: true


      - name: "Setup environment"
        run: npm ci
              
      - name: "Create .npmrc"
        run: |
            echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> ~/.npmrc
            echo "@originalworks:registry=https://npm.pkg.github.com" >> ~/.npmrc
        
      - name: "Publish"
        run: |
          cd libs/contracts-typechain
          sed -i 's/@royalty-loans\//@originalworks\//' package.json
          npm publish 
